include: package:leancode_lint/analysis_options.yaml

custom_lint:
  rules:
    - use_design_system_item:
      AocScaffold:
        - instead_of: Scaffold
          from_package: flutter
      AocIcon:
        - instead_of: Icon
          from_package: flutter

analyzer:
  enable-experiment:
    - macros
    - enhanced-parts
    - augmentations
  plugins:
    - custom_lint
  exclude:
    - "**.g.dart"
    - "lib/l10n/*.dart"
