include: package:leancode_lint/analysis_options.yaml

plugins:
  aoc_lint:
    path: tools/aoc_lint

analyzer:
  exclude:
    - "**.g.dart"
    - "lib/l10n/*.dart"
    - build/**
    - android/**
    - macos/**
    - linux/**

linter:
  rules:
    migrate_design_widgets: true
