include: package:leancode_lint/analysis_options.yaml

custom_lint:
  rules:
    - use_design_system_item:
      AocScaffold:
        - instead_of: Scaffold
          from_package: flutter
      AocIcon:
        - instead_of: Icon
          from_package: flutter

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**.g.dart"